<a href="https://colab.research.google.com/github/Sahilrana-063/Frist-sem-project3/blob/main/Class_Python_for_generative_AI_and_data_science_in_shoolini_university.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
x = 10
x

10

In [2]:
print(x)

10


In [3]:
 #Rules for naming of variable

# 1. Starting position of variable is letter or under score

In [4]:
my_sub = "Data science"
print(my_sub)

Data science


In [5]:
_mycity = "Solan"
print(_mycity)

Solan


#2. Remaining part of variable are letter, underscore or number

In [6]:
my_sub1 = "Generative AI"
print(my_sub1)

Generative AI


In [7]:
1mycity = "shimla"
print(1mycity)

SyntaxError: invalid decimal literal (<ipython-input-7-dd735318f63f>, line 1)

In [65]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [8]:
#operater
# addition(+)
2+2

4

In [9]:
x = 2
y = 2
z = x+y
print(z)

4


In [10]:
#expontial(**)
2**5

32

In [11]:
#modulus(%)
5%2

1

In [12]:
#division(/)
4/2

2.0

In [13]:
#floor division(//)
5//2

2

In [14]:
5//2.2

2.0

In [15]:
#assignment operater(=)
x = 2
print(x)

2


In [16]:
a = 20
b = 10
print(a==b)

False


In [17]:
print(a!=b)

True


In [18]:
print(a>b)

True


In [19]:
print(a<b)

False


In [20]:
x = 10
y = 10
print(x>=y)

True


In [21]:
print(x<=y)

True


In [22]:
#logical operater
x = 5
print(x>2 and x<10)

True


In [23]:
print(x>2 and x>10)

False


In [24]:
a = 10
print(x>2 or x>10)

True


In [25]:
a = 10
print(not(x>2 or x>10))

False


In [26]:
my_city = "Solan"
"S" in my_city

True

In [27]:
"Z" in my_city

False

In [28]:
"S" not in my_city

False

In [29]:
"Z" not in my_city

True

In [30]:
my_city = 'Solan'
type(my_city)

str

In [31]:
my_capital = "Shimla"
type(my_capital)

str

In [32]:
my_state = '''Himachal Pradesh'''
type(my_state)

str

In [33]:
my_city

'Solan'

In [34]:
len(my_city)

5

In [35]:
#concatenation---addition of list
list1 = [34, 67, 89]
list2 = [99, 87, 65]
my_list = list1 + list2
print(my_list)

[34, 67, 89, 99, 87, 65]


In [36]:
#append() -add item into the list at end
my_list = [89, 76, 54]
my_list.append(100)
print(my_list)

[89, 76, 54, 100]


In [37]:
my_list

[89, 76, 54, 100]

In [38]:
list1 = [122, 5657, 90]
my_list.extend(list1)
print(my_list)

[89, 76, 54, 100, 122, 5657, 90]


In [39]:
#pop --- remove the item from the list with the help of index
my_list = [23, 45, 67, 80]
my_list.pop()

80

In [40]:
print(my_list)

[23, 45, 67]


In [41]:
my_list.pop(0)

23

In [42]:
my_list

[45, 67]

In [43]:
my_list = [100, 445, 78, 90]
my_list.remove(100)
my_list

[445, 78, 90]

In [44]:
my_list = [234, 789, 67, 45, 67, 89, 67]
my_list.index(67, 3,6)

4

In [45]:
my_list = [3, 5, 6, 3, 4, 2, 1]
my_list.sort(reverse = True)
my_list

[6, 5, 4, 3, 3, 2, 1]

In [46]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
list3 = [7, 8, 9]
my_list = [list1, list2, list3]
print(my_list)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [47]:
my_list[1][1]

5

In [48]:
my_list[-2][-2]

5

In [49]:
my_tuple = (1, 2, 3)
type(my_tuple)

tuple

In [50]:
my_tuple = (1, 2, 3)
type(my_tuple)

tuple

In [51]:
x = 1, 2, 3
type(x)

tuple

In [52]:
y = ()
type(y)

tuple

In [53]:
z = (True)
type(z)

bool

In [54]:
a = ("solan",)
type(a)

tuple

In [55]:
my_tuple1 = ("apple", 3.24, 8, True, None) #hetrogenius
type(my_tuple1)

tuple

In [56]:
my_tuple2 = (89, 78, 65, 34)
type(my_tuple2)

tuple

In [57]:
state_list = ["HP", "UP", "MP", "PUN", "DELHI"]
capital_list = ["SHM", "LK", "BH", "CHD", "ND"]
x = zip(state_list, capital_list)
x

In [58]:
list(x)

[('HP', 'SHM'), ('UP', 'LK'), ('MP', 'BH'), ('PUN', 'CHD'), ('DELHI', 'ND')]

In [59]:
my_tuple = (45, 78, 45, 89, 70)
my_tuple.count(45) #this method count number of perticular item

2

In [60]:
my_tuple.index(78) #this method return index of item

1

In [61]:
#concatenation--addition of data structure
tuple1 = (1, 3, 4)
tuple2 = (5, 6, 7)
tuple3 = tuple1 + tuple2
print(tuple3)

(1, 3, 4, 5, 6, 7)


In [62]:
y = list(tuple3)
y

[1, 3, 4, 5, 6, 7]

In [63]:
tuple(y)

(1, 3, 4, 5, 6, 7)

In [66]:
#immutability
my_tuple = (1, 2, 3)
my_tuple[0] = 10

TypeError: 'tuple' object does not support item assignment

In [67]:
#set -- collection of unique number of item, non empty set represented by curly braces and item seprated by comma
my_set = {6, 8, 9, 10}
type(my_set)

set

In [68]:
a = " "
type(a)

str

In [69]:
b = []
type(b)

list

In [73]:
c = ()
type(c)

tuple

In [72]:
d = {}
type(d)

dict

In [71]:
empty_set = set()
type(empty_set)

set

In [70]:
a = set()
a.add(10)
a

{10}

In [79]:
a.add(20)
a

{10, 20}

In [78]:
a.add(20)
a

{10, 20}

In [77]:
my_list = [56, 90, 78, 23, 12]
print(my_list)

[56, 90, 78, 23, 12]


In [76]:
my_set = {56, 90, 78, 23, 12}
print(my_set)

{23, 56, 90, 12, 78}


In [75]:
my_set = {89, 45, 67, 78}
my_set.update((100, 200, 50))
print(my_set)

{67, 100, 200, 45, 78, 50, 89}


In [151]:
my_set.remove(67)
my_set

KeyError: 67

In [81]:
#union--all unique number of item of the set
A= {1, 2, 3, 4, 5}
B = {4, 5, 6, 7, 8}
A.union(B)

{1, 2, 3, 4, 5, 6, 7, 8}

In [82]:
A.intersection(B) #comman item of the set

{4, 5}

In [83]:
#difference
A.difference(B)

{1, 2, 3}

In [84]:
B.difference(A)

{6, 7, 8}

In [85]:
A.symmetric_difference(B)

{1, 2, 3, 6, 7, 8}

In [87]:
#dictionary ---collection of key value pair,enclosed by curly braces({})
#key value pair is known as item and every item seprated by comma(,)
#key and value seprated by colan(:)
my_dict = {"HP":"SHM", "UP":"LK", "MP":"BH"}
type(my_dict)

dict

In [88]:
#dictionay---it is mutable
#key --it is immutable
#value -- it is mutable or immutable

In [89]:
my_dict = {"HP":"SHM", "UP":"LK", "MP":"BH"}
type(my_dict)

dict

In [90]:
my_dict = {"Name" :"Jagat", "Marks_list": [67, 87, 56, 90]}
print(my_dict)

{'Name': 'Jagat', 'Marks_list': [67, 87, 56, 90]}


In [93]:
my_dict = {"Name" :"Jagat", "Marks_list": [67, 87, 56, 90]}
print(my_dict)

{'Name': 'Jagat', 'Marks_list': [67, 87, 56, 90]}


In [92]:
my_dict.update({"college":"IIT Mandi"})
print(my_dict)

{'Name': 'Jagat', 'Marks_list': [67, 87, 56, 90], 'college': 'IIT Mandi'}


In [91]:
#keys()-- this method return the keys of your dictionary
list(my_dict.keys())

['Name', 'Marks_list']

In [98]:
#Values()-- this method return the values of your dictionary
list(my_dict.values())

['Jagat', [67, 87, 56, 90]]

In [97]:
list(my_dict.items())

[('Name', 'Jagat'), ('Marks_list', [67, 87, 56, 90])]

In [96]:
my_dict["Name"]

'Jagat'

In [95]:
my_dict.get("City", "Not found")

'Not found'

In [94]:
#if condition:
     #Code
#elif condition:
      #code
#else:
  #code

In [99]:
age = int(input("Enter your age :"))
if age <=21:
  print("You are too young for marriage")
elif age >= 60:
  print("You are too old for marriage")
else:
  print("we will find your perfect match")


Enter your age :29
we will find your perfect match


In [100]:
#for loop -- apply on sequence(list, tuple, string, range())
my_city = "Solan"
for char in my_city:
  print(char)

S
o
l
a
n


In [101]:
#indexing
for i in range(0, 5, 1):
  print(i)

0
1
2
3
4


In [102]:
for i in range(5):
  print(i)

0
1
2
3
4


In [103]:
#indexing
my_sub = "Machine learning"
for i in range(len(my_sub)): #range(16)
  print(my_sub[i], i)

M 0
a 1
c 2
h 3
i 4
n 5
e 6
  7
l 8
e 9
a 10
r 11
n 12
i 13
n 14
g 15


In [106]:
my_sub = "Machine learning"
for i in range(-1, -(len(my_sub)+1), -1): #range(16)
  print(my_sub[i], i)

g -1
n -2
i -3
n -4
r -5
a -6
e -7
l -8
  -9
e -10
n -11
i -12
h -13
c -14
a -15
M -16


In [105]:
#while loop --this loop execute upto condition is true
i = 0 #initialization
while i<5: #condition
  print(i)
  i+=1 #increment
print(i)

0
1
2
3
4
5


In [104]:
#loop control statement
i = 0
while i<5:#condition
  i+=1  #increment
  if i ==3:
    break  #break the loop
    print(i)
  else:
    print(i)

1
2


In [109]:
i = 0
while i<5:#condition
  i+=1  #increment
  if i ==3:
    continue  #skip the current iteration
    print(i)
  else:
    print(i)

1
2
4
5


In [108]:
i = 0
while i<5:#condition
  i+=1  #increment
  if i ==3:
    pass  #it is does nothing only pass
    print(i)
  else:
    print(i)

1
2
3
4
5


In [107]:
#user defined function
def add(): #this function use addition of two number
  a = int(input("Enter first number: "))
  b = int(input("Enter second number: "))
  c = a+b
  print(c)
  return c

In [110]:
print(add())

Enter first number: 2
Enter second number: 6
8
8


In [111]:
#caculation of two number
#positional arguments
def calculation(a, b):
  add = a+b
  sub = a-b
  mul = a*b
  div = a/b
  return add, sub, mul, div



In [112]:
calculation(5, 10)

(15, -5, 50, 0.5)

In [113]:
#default argument, this function use addition of two numbers
def add(a = 20, b = 30):
  c = a+b
  return c


In [114]:
print(add(90, 50))

140


In [115]:
#keyword argument
def interest(p, r, t):
  i = (p*r*t)/100
  return i

In [116]:
print(interest(t = 2, r = 10, p = 1000))

200.0


In [120]:
print(interest(1000, r = 10, t = 2))

200.0


In [119]:
print(interest(p = 1000, r = 10, 2))

SyntaxError: positional argument follows keyword argument (<ipython-input-119-82f65391e6c0>, line 1)

In [118]:
#variable length argument
#non keyword variable length argument
def test(*args):
  print(args)
  print(type(args))
  print(len(args))

In [121]:
test(4, 6, 7, 8, 9, 3)

(4, 6, 7, 8, 9, 3)
<class 'tuple'>
6


In [122]:
def addition(*args):
  sum = 0
  for i in args:
    sum+=i
  return sum

In [125]:
addition(2, 3, 10, 20, 89, 78, 56, 45, 34)

337

In [124]:
#keyword variable length arguments
def test(**kwargs):
  print(kwargs)
  print(type(kwargs))
  print(len(kwargs))

In [126]:
test(a = 10, b = 20, c = 30)

{'a': 10, 'b': 20, 'c': 30}
<class 'dict'>
3


In [127]:
def pass_students(**kwargs):
  pass_student_list = []
  for name, marks in kwargs.items():
    if marks >= 35:
      pass_student_list.append(name)
  return pass_student_list

In [131]:
pass_students(A = 30, B = 78, C = 65, D = 23)

['B', 'C']

In [130]:
#how import numpy
import numpy as np

In [132]:
#one dimensional array
oned_array = np.array([1, 4, 7])
print(oned_array)

[1 4 7]


In [133]:
#two dimensional array
twod_array = np.array([[7, 8, 9],[4, 5, 6]])
print(twod_array)

[[7 8 9]
 [4 5 6]]


In [137]:
threed_array = np.array([[[8, 9, 6],[5, 4, 3]],
                        [[9, 6, 5],[3, 4, 5]]])
print(threed_array)

[[[8 9 6]
  [5 4 3]]

 [[9 6 5]
  [3 4 5]]]


In [136]:
#array inspection
oned_array = np.array([1, 4, 7])
print(oned_array)

[1 4 7]


In [135]:
#shape
oned_array.shape

(3,)

In [134]:
print(twod_array)

[[7 8 9]
 [4 5 6]]


In [144]:
twod_array.shape

(2, 3)

In [143]:
threed_array = np.array([[[8, 9, 6],[5, 4, 3]],
                        [[9, 6, 5],[3, 4, 5]]])
print(threed_array)

[[[8 9 6]
  [5 4 3]]

 [[9 6 5]
  [3 4 5]]]


In [142]:
threed_array.shape

(2, 2, 3)

In [141]:
# number of dimension of array
threed_array.ndim

3

In [140]:
#two dimensional array
twod_array = np.array([[7, 8, 9],[4, 5, 6]])
print(twod_array)
twod_array.ndim

[[7 8 9]
 [4 5 6]]


2

In [139]:
# how to find size of array
twod_array.size

6

In [138]:
#how to find data type of the array
print(twod_array)
twod_array.dtype

[[7 8 9]
 [4 5 6]]


dtype('int64')

In [148]:
#how to change data type of array
twod_array.astype(float)

array([[7., 8., 9.],
       [4., 5., 6.]])

In [147]:
#  how to create zero element array
zeros_array = np.zeros((3, 4), dtype = int)
print(zeros_array)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [146]:
ones_array = np.ones((3, 4), dtype = int)*100
print(ones_array)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


In [145]:
my_array = np.full((3, 4), 100)
print(my_array)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
